{{- if and .Values.curator.enabled .Values.curator.serviceAccount.create .Values.curator.rbac.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "elasticsearch.curator.serviceAccountName" . }}
  labels: {{- include "elasticsearch.labels" . | nindent 4 }}
    role: curator
{{- end }}
