apiVersion: v1
kind: Service
metadata:
  name: {{ include "cfg-center.fullname" . }}
  labels:
    senses: cfg-center
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      nodePort: {{ .Values.service.nodePort }}
  selector:
    senses: cfg-center
